name: Devops

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: server1
    steps:
    - name: Print hostname 
      run: |
        hostname
        ip a
        echo " i am build stage"
  test:
    needs: build
    runs-on: server1

    steps:
    - name: Print hello world
      run: |
        ip a
        echo " i am test stage"
  release:
    needs: test
    runs-on: server1

    steps:
    - name: Print hostname
      run: |
        hostname
        ip a
        echo "this is release"
