name: Devops

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - run: |
        hostname
        ip a
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        # pip install -r requirement.txt
    - name: Run Tests
      run: |
        python app/manage.py test
