name: Devops

on:
  push:
    branches: [ "main" ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Print hostname 
    - run: |
        hostname
        ip a
        echo " i am build stage"
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Print hello world
    - run: |
        echo " i am test stage"
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Print hostname
    - run: |
        echo "this is release"
